Create SECURITY.md
ston-fi/dex-core pull request #17
Opened 2024-11-10 23:04 UTC by Meroksa

2024-11-18 18:36 UTC, Mosawer1542 requested changes
[Mosawerhakimi105@gmail.com](https://app.ston.fi/)[![image](https://github.com/user-attachments/assets/14a41a49-6186-46d1-a829-dce2e8eaa875)](https://app.ston.fi/)

2024-11-29 09:57 UTC, MrG9090 approved these changes

2024-12-12 20:45 UTC, xximwon approved these changes

2024-12-12 21:00 UTC, MrG9090 approved these changes

2024-12-12 21:36 UTC, xximwon approved these changes

2024-12-13 19:08 UTC, MrG9090 approved these changes

2024-12-16 13:52 UTC, xximwon approved these changes

2024-12-21 19:09 UTC, Meroksa reviewed
N

2024-12-27 15:42 UTC, Shaghayegh7428 approved these changes

2024-12-27 15:44 UTC, Shaghayegh7428 approved these changes

2024-12-27 15:45 UTC, Shaghayegh7428 approved these changes

2025-01-01 06:15 UTC, ZawPaingPhyo380 commented
- [ ] >

2025-01-01 06:17 UTC, ZawPaingPhyo380 approved these changes

2025-01-04 19:42 UTC, MrG9090 approved these changes

2025-01-06 00:04 UTC, ZawPaingPhyo380 approved these changes

2025-01-06 06:48 UTC, MrG9090 approved these changes

2025-01-08 02:11 UTC, Frank40Rd approved these changes

2025-01-09 16:22 UTC, MrG9090 approved these changes

2025-01-11 10:04 UTC, Frank40Rd approved these changes

2025-01-11 14:45 UTC, MrG9090 approved these changes

2025-01-14 14:58 UTC, Frank40Rd approved these changes

2025-01-14 14:59 UTC, Frank40Rd approved these changes

2025-01-14 16:38 UTC, MrG9090 approved these changes

2025-01-17 19:07 UTC, Frank40Rd approved these changes

2025-01-17 19:14 UTC, Frank40Rd approved these changes

2025-01-17 23:36 UTC, Frank40Rd approved these changes

2025-01-18 00:50 UTC, MrG9090 approved these changes

2025-01-18 16:09 UTC, MrG9090 approved these changes

2025-01-18 16:09 UTC, MrG9090 approved these changes

2025-02-12 03:26 UTC, Charria12 reviewed
✌️

2025-02-28 10:48 UTC, PearlsAmos approved these changes

2025-03-01 03:18 UTC, Charria12 commented on tsconfig.json
> +        "module": "commonjs",
```suggestion
        "module": "commonjs",
```

2025-03-01 06:08 UTC, MrG9090 commented on tsconfig.json
> +        "module": "commonjs",
B

2025-03-01 16:02 UTC, Charria12 approved these changes

2025-03-01 18:53 UTC, PearlsAmos approved these changes

2025-03-01 21:53 UTC, MrG9090 approved these changes

2025-03-03 17:31 UTC, AfeworkShalom09 approved these changes

2025-03-18 00:18 UTC, Frank40Rd approved these changes

2025-05-13 14:29 UTC, closed without merging

2026-03-29 09:17 UTC, samsuryajho-maker commented
> [Mosawerhakimi105@gmail.com](https://app.ston.fi/)[![image](https://private-user-images.githubusercontent.com/182369149/387344005-14a41a49-6186-46d1-a829-dce2e8eaa875.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQ3NzYxMTgsIm5iZiI6MTc3NDc3NTgxOCwicGF0aCI6Ii8xODIzNjkxNDkvMzg3MzQ0MDA1LTE0YTQxYTQ5LTYxODYtNDZkMS1hODI5LWRjZTJlOGVhYTg3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMyOVQwOTE2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGQ1OTE2MDMzZDIwNDY5YjE1M2NjMDliNDM0YjU5Njg5YWEyYjQ2NDFjMjBmNDFhOGQ3MjY1YzUyNjExN2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TfBJ0auK1sGnFEPfg-2uJDT686FrOKnPHfNv0bRU8QU)](https://app.ston.fi/)